### ISSUE TITLE
MAGinator: Cherry pick catalogues

### ISSUE THREAD

**Issue by HenrikSpiegel** [HenrikSpiegel/Screener#33]
We have found that the MAGinator routine appears to work on a subset of the catalogues.

Before we start and try to build a hot-start setup to ensure the best possible start for MAGinator, we wish to find proof that the MAGinator process actually result in better quantification.

### Cherry pick catalogues.
Select catalogues which appear to be working. 
- The MSE should be better between init and best
- The distribution of counts smaller.
__We allow ourselves to drop the rRNA containing group eventhough it fullfills these criteria__

### Measure of improvement.
We shall initially compare MAG_init and MAG_best and then include All_5000.

Which metric shall we be using?

We are interested in two aspects:
1. Can we estimate the underlying "True" amount of the BGC [Accuracy].
  - Here we will use two different truths: 
    - Average depth of BGC = Average depth of genome which can be derived from the amount of reads drawn from the genome by CAMISIM
    - Actual median coverage depth of BGC. Found from the CAMISIM bamfile output.
2. Consistency of the estimate [Precision].
  - We could argue that as long as the estimate is consistent we can still use it.
    - Most analysis would work with comparisons between samples. Ie do we have more BGC-X in sample a than in sample b. Thus, when doing the comparison we do not need to have a perfect estimate but if both samples are consistently x% off that missing accuracy becomes a non-problem.

**NB**: We wish to test the catalogue across various datasets sizes, therefore we will use the MRAE (mean relative absolute error) since that is not estimation size dependent. 

###Tasks

- [x] Cherry-pick a number of good looking catalogues.
- [x] Test the catalogues across datasets and samples quantifying both _accuracy_ and _precision_.
- [x] Test following both individually and summed versions. Ie. within a dataset is the _accuracy_ and _precision_ higher for MAG_best compared to MAG_init
- [x] Compare this to all_5000 (Here my guess is the all_5000 will generally perform well but perhaps with worse precision?)
- [x] ABV (Always be visualizing)
